---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Configure Nginx reverse proxy
  ansible.builtin.template:
    src: mywebapp.conf.j2
    dest: /etc/nginx/sites-available/mywebapp.conf
  notify: reload nginx

- name: Enable Nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/mywebapp.conf
    dest: /etc/nginx/sites-enabled/mywebapp.conf
    state: link

- name: Remove default Nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Ensure Nginx is running
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes